【コードレビュー対応】ActiveStorage・ActionCable関連以外の指摘箇所を修正
taka61/chiikoma pull request #84
Opened 2022-03-12 05:25 UTC by taka61

コードレビュー内容
https://bootcamp.fjord.jp/products/11430

## 内容
* [今週の月曜日・日曜日の日付](https://github.com/taka61/chiikoma/blob/main/app/controllers/hassles/achievement_controller.rb#:~:text=def%20format_date,end)の取得方法を変更しました
* [変数名](https://github.com/taka61/chiikoma/blob/main/app/controllers/hassles/achievement_controller.rb#:~:text=def-,fetch_registration_info,-%40registration_numbers%20%3D%20%40data.where)を変更しました
* Controllerに書いていたメソッドの一部をUser Modelのメソッドとしてまとめました
* [未解決ちいこま一覧取得](https://github.com/taka61/chiikoma/blob/main/app/controllers/api/hassles_controller.rb#:~:text=%40hassles%20%3D%20current_user.hassles.where(solved%3A%20false).order(total_points%3A%20%3Adesc))をscopeメソッドとしてまとめました
*  [解決済みちいこま一覧取得](https://github.com/taka61/chiikoma/blob/main/app/controllers/api/hassles_controller.rb#:~:text=%40hassles%20%3D%20current_user.hassles.where(solved%3A%20true).order(total_points%3A%20%3Adesc))をscopeメソッドとしてまとめました

2022-03-13 13:19 UTC, komagata commented on app/controllers/hassles/achievement_controller.rb
> +    def fetch_all_chiikoma
chiikomaとhasslessは同じ意味のものを指しているので後者に統一した方がいいかもです〜

また、外部から使う必要のないものはprivateメソッドにするのがいいとおもいます。

2022-03-13 13:19 UTC, komagata commented on app/controllers/hassles/achievement_controller.rb
>        @all_chiikoma_numbers = @registration_numbers + @solution_numbers
これはUserのメソッドとしてまとめられるかもと思いました〜。

2022-03-13 13:19 UTC, komagata commented on app/models/hassle.rb
> +  scope :order_for_not_solved_list, -> { where(solved: false).order(total_points: :desc) }
orderとあるということは何かのlistであることは自明なので`order_for_not_solved`でいいかもです〜

2022-03-17 05:49 UTC, taka61 commented on app/models/hassle.rb
> +  scope :order_for_not_solved_list, -> { where(solved: false).order(total_points: :desc) }
ご指摘頂いた`order_for_not_solved`に変更しました🙏

2022-03-17 05:49 UTC, taka61 commented on app/controllers/hassles/achievement_controller.rb
>        @all_chiikoma_numbers = @registration_numbers + @solution_numbers
User Modelにてメソッドとしてまとめました。
駒形さんの意図していた通りになっているか、確認の程よろしくお願いします🙏

2022-03-17 05:49 UTC, taka61 commented on app/controllers/hassles/achievement_controller.rb
> +    def fetch_all_chiikoma
変数名のアドバイスありがとうございます。
`hassles`で統一しました🙆‍♀️
またコントローラー内でしか使用しないメソッドをPrivateに変更しました!

2022-03-18 02:13 UTC, komagata commented on app/controllers/hassles/achievement_controller.rb
> +      @registration_hassles_and_solution_hassles = current_user.show_chart
viewの中での使い方次第ですが、current_userからのメソッド呼び出し一つで取得できる値であれば一旦インスタンス変数に入れずにviewの中で直接呼び出すとスマートになるかもです〜。

2022-03-20 03:46 UTC, taka61 commented on app/controllers/hassles/achievement_controller.rb
> +      @registration_hassles_and_solution_hassles = current_user.show_chart
>current_userからのメソッド呼び出し一つで取得できる値であれば一旦インスタンス変数に入れずにviewの中で直接呼び出すとスマートになるかもです〜。

確かにインスタンス変数に入れるメリットがあまりないですね〜！
viewの中で直接呼び出す形へ変更しました。

2022-03-23 01:43 UTC, komagata commented on app/controllers/hassles/achievement_controller.rb
> +      display_one_week
このメソッドを他からも使うのでなければ、メソッド化しなくていいかもです〜

2022-03-23 01:43 UTC, komagata commented on app/models/user.rb
> +  def fetch_registration_numbers
modelで自分でメソッドを追加した場合は、基本的にすべてテストが欲しいですね。

2022-03-23 07:14 UTC, taka61 commented on app/controllers/hassles/achievement_controller.rb
> +      display_one_week
ご指摘ありがとうございます!
`display_one_week`もviewの中で直接呼び出す形へ変更しました。

2022-03-23 07:17 UTC, taka61 commented on app/models/user.rb
> +  def fetch_registration_numbers
ご指摘ありがとうございます!
Userモデルに書いたメソッドのテストを`test/models/user_test.rb`に追加しました。

2022-03-23 07:29 UTC, komagata requested changes

2022-03-23 07:29 UTC, komagata commented on app/controllers/hassles/achievement_controller.rb
> +    def index; end
すごくスッキリしましたね！

2022-03-23 07:29 UTC, komagata commented on test/models/user_test.rb
> +  test "the truth" do
the truthだと何をテストしてるのか「テスト名」からわからないかもです〜

2022-03-23 08:45 UTC, taka61 commented on test/models/user_test.rb
> +  test "the truth" do
>the truthだと何をテストしてるのか「テスト名」からわからないかもです〜

抽象的になっていました…！
具体的なテスト名`email address and password are filled in`へ変更しました🙏

2022-03-24 05:10 UTC, komagata reviewed
確認しました、OKですー🙆‍♂️

2022-04-04 06:13 UTC, merged